name: Test and deploy

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1
  
jobs:
  create_s3_bucket:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2.0.3
      
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform
      
      - name: Terraform validate
        run: terraform validate
        working-directory: ./terraform
      
      - name: Terraform plan
        run: terraform plan
        working-directory: ./terraform
      
      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        
      - name: Terraform destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
